### ISSUE TITLE
sh apply.sh - doesn't work when using multipass

### ISSUE THREAD

**Issue by thomassuedbroecker** [cloud-native-toolkit/automation-solutions#215]
# Problem

When I execute the `sh apply.sh` command in a multipass vm terminal I get following outputs:

* First problem:

```sh
ubuntu@cli-tools:/automation/ibm-vpc-roks-argocd-ubi$ sh apply.sh
apply.sh: 6: [[: not found
apply.sh: 11: [[: not found
apply.sh: 11: [[: not found
apply.sh: 16: [[: not found
apply.sh: 21: [[: not found
apply.sh: 39: [[: not found
apply.sh: 46: [[: not found
apply.sh: 64: [[: not found
apply.sh: 39: [[: not found
apply.sh: 46: [[: not found
```

* Second problem:

```sh
 Error: Unsupported argument
│ 
│   on main.tf line 160, in module "terraform-gitops-ubi":
│  160:   cluster_ingress_hostname = var.terraform-gitops-ubi_cluster_ingress_hostname
│ 
│ An argument named "cluster_ingress_hostname" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 162, in module "terraform-gitops-ubi":
│  162:   enable_sso = var.terraform-gitops-ubi_enable_sso
│ 
│ An argument named "enable_sso" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 168, in module "terraform-gitops-ubi":
│  168:   tls_secret_name = var.terraform-gitops-ubi_tls_secret_name
│ 
│ An argument named "tls_secret_name" is not expected here.
```

# Steps to reproduce

### Step 1: Using following files:

1. `credentials.properties`

```sh
export TF_VAR_gitops_repo_token=XXX
export TF_VAR_ibmcloud_api_key=XXX
```

2. `BOM`

```yaml
apiVersion: cloudnativetoolkit.dev/v1alpha1
kind: BillOfMaterial
metadata:
  name: ibm-vpc-roks-argocd-ubi
spec:
  modules:
    # Virtual Private Cloud - related
    # - subnets
    # - gateways
    - name: ibm-vpc
      alias: ibm-vpc
      version: v1.16.1
      variables:
      - name: name
        value: "tsued-gitops-ubi"
      - name: tags
        value: ["tsuedro"]
    - name: ibm-vpc-subnets
      alias: ibm-vpc-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 1
        - name: name
          value: "tsued-gitops-ubi"
        - name: tags
          value: ["tsuedro"]
    - name: ibm-vpc-gateways
    # ROKS - related
    # - objectstorage
    - name: ibm-ocp-vpc
      alias: ibm-ocp-vpc
      version: v1.15.7
      variables:
        - name: name
          value: "tsued-gitops-ubi"
        - name: worker_count
          value: 2
        - name: tags
          value: ["tsuedro"]
    - name: ibm-object-storage
      alias: ibm-object-storage
      version: v4.0.3
      variables:
        - name: name
          value: "cos_tsued_ubi"
        - name: tags
          value: ["tsuedro"]
        - name: label
          value: ["cos_tsued_ubi"]
    # Install OpenShift GitOps and Bootstrap GitOps (aka. ArgoCD) - related
    # - argocd
    # - gitops
    - name: argocd-bootstrap
      alias: argocd-bootstrap
      version: v1.12.0
      variables:
        - name: repo_token
    - name: gitops-repo
      alias: gitops-repo
      version: v1.20.2
      variables:
        - name: host
          value: "github.com"
        - name: type
          value: "GIT"
        - name: org
          value: "thomassuedbroecker"
        - name: username
          value: "thomassuedbroecker"
        - name: project
          value: "iascable-gitops-ubi"
        - name: repo
          value: "iascable-gitops-ubi"
    # Install ubi
    # New custom module linked by the custom catalog
    - name: terraform-gitops-ubi
```

### Step 2: Execute following command to create the output: 

```sh
BASE_CATALOG=https://modules.cloudnativetoolkit.dev/index.yaml
CUSTOM_CATALOG=https://raw.githubusercontent.com/Vishal-Ramani/UBI-helm-module-example/main/example/catalog/ubi-helm-catalog.yaml

iascable build -i ibm-vpc-roks-argocd-ubi.yaml -c $BASE_CATALOG -c $CUSTOM_CATALOG
```

# Environment

* iascable --version 2.17.4 
* macos version 12.5.1
* multipass version: multipass   1.10.1+mac, multipassd  1.10.1+mac
* vpn: not active
* multipass volume mapped and working
